language: python
python:
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "npm install"
  - "node_modules/.bin/bower install"
  - "node_modules/.bin/gulp --production"
script:
  - "flake8 --max-line-length=150 --statistics openslides tests"

  - "DJANGO_SETTINGS_MODULE='tests.settings' coverage run ./manage.py test tests.unit"
  - "coverage report --show-missing --fail-under=35"

  - "DJANGO_SETTINGS_MODULE='tests.settings' coverage run ./manage.py test tests.integration"
  - "coverage report --show-missing --fail-under=45"

  - "DJANGO_SETTINGS_MODULE='tests.old.settings' ./manage.py test tests.old"
