dist: xenial
sudo: true

matrix:
  include:
    - language: python
      cache:
        pip: true
      python:
        - "3.6"
      install:
        - python --version
        - pip install --upgrade setuptools pip
        - pip install --upgrade --requirement requirements/development.txt
        - pip install --upgrade .[big_mode]
        - pip freeze
      script:
        - flake8 openslides tests
        - isort --check-only --diff --recursive openslides tests
        - python -m mypy openslides/ tests/
        - python -W ignore -m pytest --cov --cov-fail-under=70

    - language: python
      cache:
        pip: true
      python:
        - "3.7"
      install:
        - python --version
        - pip install --upgrade setuptools pip
        - pip install --upgrade --requirement requirements/development.txt
        - pip install --upgrade .[big_mode]
        - pip freeze
      script:
        - flake8 openslides tests
        - isort --check-only --diff --recursive openslides tests
        - python -m mypy openslides/ tests/
        - python -W ignore -m pytest --cov --cov-fail-under=70

    - language: node_js
      node_js:
        - "10.5"
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
      cache:
        directories:
          - node_modules
      before_install:
        - sh -e /etc/init.d/xvfb start
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - npm install -g @angular/cli
        - ng --version
        - cd client
      install:
        - npm install
      script:
        - npm run lint
        - ng test --watch=false

    - language: node_js
      node_js:
        - "10.5"
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
      cache:
        directories:
          - node_modules
      before_install:
        - sh -e /etc/init.d/xvfb start
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - npm install -g @angular/cli
        - ng --version
        - cd client
      install:
        - npm install
      script:
        - ng build

    - language: node_js
      node_js:
        - "10.5"
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
      cache:
        directories:
          - node_modules
      before_install:
        - sh -e /etc/init.d/xvfb start
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - npm install -g @angular/cli
        - ng --version
        - cd client
      install:
        - npm install
      script:
        - ng build --prod
