dist: xenial
sudo: true

matrix:
  include:
    - language: python
      cache:
        pip: true
      python:
        - "3.6"
      install:
        - python --version
        - pip install --upgrade setuptools pip
        - pip install --upgrade --requirement requirements/development.txt
        - pip install --upgrade .[big_mode]
        - pip freeze
      script:
        - flake8 openslides tests
        - isort --check-only --diff --recursive openslides tests
        - python -m mypy openslides/
        - python -W ignore -m pytest --cov --cov-fail-under=75

    - language: python
      cache:
        pip: true
      python:
        - "3.7"
      install:
        - python --version
        - pip install --upgrade setuptools pip
        - pip install --upgrade --requirement requirements/development.txt
        - pip install --upgrade .[big_mode]
        - pip freeze
      script:
        - flake8 openslides tests
        - isort --check-only --diff --recursive openslides tests
        - python -m mypy openslides/
        - python -W ignore -m pytest --cov --cov-fail-under=75

    - language: node_js
      node_js:
        - "10.5"
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
      cache:
        yarn: true
        directories:
          - $HOME/.yarn-cache
          - node_modules
      before_install:
        - sh -e /etc/init.d/xvfb start
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
        - yarn global add @angular/cli
        - ng --version
        - cd client
      install:
        - yarn install
      script:
        - yarn run lint
        - yarn run test --watch=false
