version: '3'
services:
    datastore-reader:
        image: openslides-datastore-reader-dev
        volumes:
            - ./openslides-datastore-service/shared/shared:/app/shared
            - ./openslides-datastore-service/reader/reader:/app/reader
    datastore-writer:
        image: openslides-datastore-writer-dev
        volumes:
            - ./openslides-datastore-service/shared/shared:/app/shared
            - ./openslides-datastore-service/writer/writer:/app/writer
            - ./cli:/app/cli
    client:
        image: openslides-client-dev
        volumes:
            - ./openslides-client/client/src:/app/src
    backend:
        image: openslides-backend-dev
        volumes:
            - ./openslides-backend/openslides_backend:/srv/code/openslides_backend
    autoupdate:
        image: openslides-autoupdate-dev
        volumes:
            - ./openslides-autoupdate-service/cmd:/app/cmd
            - ./openslides-autoupdate-service/internal:/app/internal
    haproxy:
        image: openslides-haproxy-dev
        volumes:
            - ./haproxy/src:/usr/local/etc/haproxy