version: "3"
services:
  # DATASTORE SECTION
  datastore-reader:
    depends_on:
      - postgres
    env_file: services.env
    environment:
      - NUM_WORKERS=8
  datastore-writer:
    depends_on:
      - postgres
      - message-bus
    env_file: services.env

  # CLIENT
  client:
    depends_on:
      - backend
      - autoupdate

  # BACKEND
  backend:
    depends_on:
      - datastore-reader
      - datastore-writer
    env_file: services.env

  # AUTOUPDATE
  autoupdate:
    depends_on:
      - datastore-reader
      - message-bus
    env_file: services.env

  # AUTH
  auth:
    depends_on:
      - datastore-reader
      - cache
    env_file: services.env
  cache:
    image: redis:latest

  # MEDIA
  media:
    depends_on:
      - backend
      - postgres
    env_file: services.env

  # PERSISTENCE
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=openslides
      - POSTGRES_PASSWORD=openslides
      - POSTGRES_DB=openslides

  # SHARED
  message-bus:
    image: redis:latest

  # UPLINK
  haproxy:
    depends_on:
      - client
      - backend
      - autoupdate
    ports:
      - "8000:8000"
