version: "3"
services:
    backend:
        image: openslides-backend
        ports:
            - "9002:9002"
        environment:
            - DATASTORE_READER_HOST=reader
            - DATASTORE_READER_PORT=9010
            - DATASTORE_WRITER_HOST=writer
            - DATASTORE_WRITER_PORT=9011
        depends_on:
            - writer
            - reader
    reader:
        image: openslides-datastore-reader
        environment:
            - DATASTORE_ENABLE_DEV_ENVIRONMENT=1
        depends_on:
            - postgresql
        ports:
            - "9010:9010"
    writer:
        image: openslides-datastore-writer
        environment:
            - DATASTORE_ENABLE_DEV_ENVIRONMENT=1
            - MESSAGE_BUS_HOST=redis
            - MESSAGE_BUS_PORT=6379
        depends_on:
            - postgresql
            - redis
    postgresql:
        image: postgres:11
        environment:
            - POSTGRES_USER=openslides
            - POSTGRES_PASSWORD=openslides
            - POSTGRES_DB=openslides
    redis:
        image: redis:alpine