version: "3"
services:
  datastore-reader:
    image: openslides-datastore-reader-dev
    depends_on:
      - postgres
    env_file: services.env
    environment:
      - DATASTORE_ENABLE_DEV_ENVIRONMENT=1
      - NUM_WORKERS=8
      - OPENSLIDES_DEVELOPMENT=1
    volumes:
      - ../openslides-datastore-service/datastore:/app/datastore
    ports:
      - 9010:9010

  datastore-writer:
    image: openslides-datastore-writer-dev
    depends_on:
      - postgres
      - message-bus
    env_file: services.env
    volumes:
      - ../openslides-datastore-service/datastore:/app/datastore
      - ../openslides-datastore-service/cli:/app/cli
    environment:
      - DATASTORE_ENABLE_DEV_ENVIRONMENT=1
      - COMMAND=create_initial_data
      - DATASTORE_INITIAL_DATA_FILE=https://raw.githubusercontent.com/OpenSlides/OpenSlides/master/docs/example-data.json
      - OPENSLIDES_DEVELOPMENT=1
    ports:
      - 9011:9011

  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=openslides
      - POSTGRES_PASSWORD=openslides
      - POSTGRES_DB=openslides

  client:
    image: openslides-client-dev
    depends_on:
      - backend
      - autoupdate
    env_file: services.env
    environment:
      - OPENSLIDES_DEVELOPMENT=1
    volumes:
      - ../openslides-client/client/src:/app/src

  backend:
    image: openslides-backend-dev
    depends_on:
      - datastore-reader
      - datastore-writer
      - auth
    env_file: services.env
    environment:
      - OPENSLIDES_DEVELOPMENT=1
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      # - EMAIL_HOST_USER username
      # - EMAIL_HOST_PASSWORD secret
      # EMAIL_CONNECTION_SECURITY use NONE, STARTTLS or SSL/TLS
      - EMAIL_CONNECTION_SECURITY=NONE
      - EMAIL_TIMEOUT=5
      - EMAIL_ACCEPT_SELF_SIGNED_CERTIFICATE=false
      - DEFAULT_FROM_EMAIL=noreply@example.com
    volumes:
      - ../openslides-backend/openslides_backend:/app/openslides_backend
      - ../openslides-backend/migrations:/app/migrations

  autoupdate:
    image: openslides-autoupdate-dev
    depends_on:
      - datastore-reader
      - message-bus
    env_file: services.env
    environment:
      - OPENSLIDES_DEVELOPMENT=1
    volumes:
      - ../openslides-autoupdate-service/cmd:/root/cmd
      - ../openslides-autoupdate-service/internal:/root/internal
      - ../openslides-autoupdate-service/pkg:/root/pkg

  icc:
    image: openslides-icc-dev
    depends_on:
      - datastore-reader
      - message-bus
      - auth
    env_file: services.env
    environment:
      - OPENSLIDES_DEVELOPMENT=1
    volumes:
      - ../openslides-icc-service/cmd:/root/cmd
      - ../openslides-icc-service/internal:/root/internal

  auth:
    image: openslides-auth-dev
    depends_on:
      - datastore-reader
      - cache
    env_file: services.env
    environment:
      - OPENSLIDES_DEVELOPMENT=1
    volumes:
      - ../openslides-auth-service/auth/src:/app/src

  cache:
    image: redis:latest

  media:
    image: openslides-media-dev
    depends_on:
      - backend
      - postgres
    env_file: services.env
    environment:
      - OPENSLIDES_DEVELOPMENT=1
    volumes:
      - ../openslides-media-service/src:/app/src

  manage:
    image: openslides-manage-dev
    depends_on:
      - auth
      - datastore-writer
    env_file: services.env
    environment:
      - OPENSLIDES_DEVELOPMENT=1
    ports:
      - "9008:9008"

  message-bus:
    image: redis:latest

  proxy:
    image: openslides-proxy-dev
    depends_on:
      - client
      - backend
      - autoupdate
    ports:
      - "8000:8000"

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "8025:8025" # web ui to check mails manually
