version: "3"
services:
  cypress:
    build: .
    image: cypress
    volumes:
      - ./results/videos :/app/cypress/videos
      - ./results/screenshots :/app/cypress/screenshots
    extra_hosts:
      host.docker.internal: host-gateway
