---
name: Announce initial-data.json updates
on:
  push:
    branches:
      - master
    paths:
      - 'docker/initial-data.json'

jobs:
  announce-update:
    name: 'Announce updates to initial-data.json'
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create Issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/announcement_templates/updates-to-initial-data.md
