name: Validate models.yml
on: [push, pull_request]
jobs:
  validate:
    name: Validate models.yml
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Install validator
      run: go get github.com/OpenSlides/openslides-modelsvalidate/cmd/modelsvalidate@v0.1.2
      env:
        GO111MODULE: on

    - name: Check out code
      uses: actions/checkout@v2

    - name: Validate models.yml
      run: $HOME/go/bin/modelsvalidate docs/models.yml