name: Validate models.yml
on: [push, pull_request]
jobs:
  validate:
    name: Validate models.yml
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build validator
      run: go build
      working-directory: docs/modelsvalidator
      env:
        GO111MODULE: on

    - name: Validate models.yml
      run: docs/modelsvalidator/modelsvalidator docs/models.yml